name: Feature Request
description: Suggest a new feature or improvement for discussion and planning.
labels: [feature]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please complete all fields to help the team understand and evaluate your feature request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the new feature or improvement.
      placeholder: e.g., "Add offline support to the mobile dashboard"
    validations:
      required: true
