name: Software Bug Report
description: Report a software issue using a structured format.

body:
  - type: markdown
    attributes:
      value: |
        Please fill in the following fields. All fields are mandatory unless marked optional.

  - type: input
    id: hw
    attributes:
      label: HW version
      placeholder: NA in case not apply
    validations:
      required: true

  - type: input
    id: sw
    attributes:
      label: SW version
      placeholder: NA in case not apply
    validations:
      required: true  

  - type: dropdown
    id: context
    attributes:
      label: Technnical Area
      description: Which technnical area is the responisble of the issue
      options:
        - Software
        - Hardware
        - Mechanic
    validations:
      required: true        

  - type: textarea
    id: description
    attributes:
      label: Issue Description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce the issue
    validations:
      required: true

  - type: input
    id: reporter
    attributes:
      label: Who found the issue
    validations:
      required: true

  - type: textarea
    id: observers
    attributes:
      label: Observers
      description: Add @names to observe this issue (optional)
