name: Software Bug Report
description: Report a software issue using a structured format.

body:
  - type: markdown
    attributes:
      value: |
        Please fill in the following fields. All fields are mandatory unless marked optional.

  - type: input
    id: hw
    attributes:
      label: HW version
      placeholder: Specify the HW version
    validations:
      required: true

  - type: input
    id: sw
    attributes:
      label: SW version
      placeholder: Specify the SW version
    validations:
      required: true  

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: |
        Quantifies how much the issue affects the system or project:
        
        **3 – Major**: Critical failure or blocker (e.g. backend crash, data loss)
        **2 – Medium**: Significant, but not blocking (e.g. feature degraded)
        **1 – Minor**: Cosmetic or low impact (e.g. small visual bug)
        
        Consider: Does it block progress? Affect safety or compliance? Is it reversible?
    options:
      1 (Minor)
      2 (Medium)
      3 (Major)
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: |
        Measures how the issue affects key project objectives:
        
        - **3 – Major**: Impacts cost, delivery, or quality significantly (e.g. budget overruns)
        - **2 – Medium**: Affects some modules or deadlines (e.g. partial replanning)
        - **1 – Minor**: Local or temporary impact (e.g. minor delay, no strategic effect)
  
        Consider: Does it affect system-wide goals, cause delays, or require contract changes?
    options:
      - 1 (Minor)
      - 2 (Medium)
      - 3 (Major)
    validations:
      required: true

  - type: dropdown
    id: relevance
    attributes:
      label: Relevance
      description: |
        How urgent or strategically sensitive is this issue?
        
        - **3 – Major**: Needs immediate action; critical for CI/CD, demos, or customer deliverables
        - **2 – Medium**: Should be addressed soon; temporary workarounds exist
        - **1 – Minor**: Can be deferred without business or client impact
  
        Ask: Does it block work today? Is it critical for the client? Is there reputational or legal risk?
    options:
      - 1 (Minor)
      - 2 (Medium)
      - 3 (Major)
    validations:
      required: true

  - type: dropdown
    id: context
    attributes:
      label: Technnical Area
      description: Which technnical area is the responisble of the issue
      options:
        - Software
        - Hardware
        - Mechanic
    validations:
      required: true        

  - type: textarea
    id: description
    attributes:
      label: Issue Description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce the issue
    validations:
      required: true

  - type: textarea
    id: reporter
    attributes:
      label: Who found the issue
      description: Tag (@) the person who reported the issue.
    validations:
      required: true

  - type: textarea
    id: observers
    attributes:
      label: Observers
      description: Optionally, tag (@) individuals who should be informed or observe this issue.
