name: Software Bug Report
description: Report a software issue using a structured format.

body:
  - type: markdown
    attributes:
      value: |
        Please fill in the following fields. All fields are mandatory unless marked optional.

  - type: input
    id: hw
    attributes:
      label: HW version
      placeholder: NA in case not apply
    validations:
      required: true

  - type: input
    id: sw
    attributes:
      label: SW version
      placeholder: NA in case not apply
    validations:
      required: true  
  
  - type: input
      id: impact
      attributes:
        label: Impact
        description: How severe is the impact of this issue? (1 = minimal, 5 = critical)
        placeholder: 1–5
      validations:
        required: true

  - type: input
    id: frequency
    attributes:
      label: Frequency
      description: How often does this issue occur? (1 = rare, 5 = always)
      placeholder: 1–5
    validations:
      required: true

  - type: input
    id: reproducibility
    attributes:
      label: Reproducibility
      description: How easily can this issue be reproduced? (1 = very hard, 5 = always reproducible)
      placeholder: 1–5
    validations:
      required: true      

  - type: dropdown
    id: context
    attributes:
      label: Technnical Area
      description: Which technnical area is the responisble of the issue
      options:
        - Software
        - Hardware
        - Mechanic
    validations:
      required: true        

  - type: textarea
    id: description
    attributes:
      label: Issue Description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce the issue
    validations:
      required: true

  - type: textarea
    id: reporter
    attributes:
      label: Who found the issue
      description: Tag (@) the person who reported the issue.
    validations:
      required: true

  - type: textarea
    id: observers
    attributes:
      label: Observers
      description: Optionally, tag (@) individuals who should be informed or observe this issue.
