name: Task
description: Create a new engineering task with detailed information and checklists.
labels: [task]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please complete all applicable sections to clearly define this task.

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Describe what needs to be done.
      placeholder: Clearly define the goal, requirements, or deliverables.
    validations:
      required: true
