name: Label with JORDI if Bug Context Found

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write  # Needed to add or create labels    

jobs:
  add-jordi-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add 'JORDI' label if 'Bug Context' is found
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || "";
            const issue_number = context.issue.number;

            if (/Bug Context/i.test(body)) {
              console.log("Bug Context found — adding label 'JORDI'");

              // Ensure label exists (create if not)
              try {
                await github.rest.issues.getLabel({
                  ...context.repo,
                  name: "JORDI"
                });
              } catch {
                await github.rest.issues.createLabel({
                  ...context.repo,
                  name: "JORDI",
                  color: "ededed",
                  description: "Auto-added when 'Bug Context' is present"
                });
              }

              // Add label to the issue
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number,
                labels: ["JORDI"]
              });
            } else {
              console.log("No Bug Context found — skipping label");
            }
