name: Label from Bug Context

on:
  issues:
    types: [opened, edited]

jobs:
  label-from-context:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Bug Context and apply label
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || "";
            const match = body.match(/Bug Context\s*\n\n\s*(.*)/i);
            if (match && match[1]) {
              const label = match[1].trim();
              console.log("Label to add:", label);
              
              // Check if label exists
              try {
                await github.rest.issues.getLabel({
                  ...context.repo,
                  name: label
                });
              } catch {
                // Create label if it doesn't exist
                await github.rest.issues.createLabel({
                  ...context.repo,
                  name: label,
                  color: "ededed",
                  description: `Auto-created from Bug Context`
                });
              }

              // Add label to issue
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: context.issue.number,
                labels: [label]
              });
            }
