name: Label from Context line

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write  # Required to add/create labels

jobs:
  label-from-context:
    runs-on: ubuntu-latest
    steps:
      - name: Extract label from Context block and apply
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || "";
            const issue_number = context.issue.number;

            // Match "Context" followed by optional whitespace/newline, then capture the next non-empty line
            const match = body.match(/Technnical Area\s*\n\s*(\S[^\n]*)/i);

            if (match && match[1]) {
              const label = match[1].trim();
              console.log(`Extracted label: ${label}`);

              // Ensure the label exists (create if not)
              try {
                await github.rest.issues.getLabel({
                  ...context.repo,
                  name: label
                });
              } catch {
                await github.rest.issues.createLabel({
                  ...context.repo,
                  name: label,
                  color: "ededed",
                  description: "Auto-created from Context section"
                });
              }

              // Add the label to the issue
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number,
                labels: [label]
              });
            } else {
              console.log("No 'Context' section found — skipping label.");
            }
